//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPlayer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting....
        /// </summary>
        internal static string Aborting {
            get {
                return ResourceManager.GetString("Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not close the project.
        /// </summary>
        internal static string CanNotCloseTheProject {
            get {
                return ResourceManager.GetString("CanNotCloseTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the view &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotFindView {
            get {
                return ResourceManager.GetString("CanNotFindView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load view &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotLoadView {
            get {
                return ResourceManager.GetString("CanNotLoadView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save the view &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotSaveView {
            get {
                return ResourceManager.GetString("CanNotSaveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        internal static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all but this.
        /// </summary>
        internal static string CloseAllButThis {
            get {
                return ResourceManager.GetString("CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to target ({0}).
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclamation.
        /// </summary>
        internal static string Exclamation {
            get {
                return ResourceManager.GetString("Exclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going online....
        /// </summary>
        internal static string GoingOnline {
            get {
                return ResourceManager.GetString("GoingOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing view &apos;{0}&apos;....
        /// </summary>
        internal static string InitializingView {
            get {
                return ResourceManager.GetString("InitializingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading view file &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingViewFile {
            get {
                return ResourceManager.GetString("LoadingViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin type &apos;{0}&apos; not found in &apos;{1}&apos;.
        /// </summary>
        internal static string PluginTypeNotFoundInAssembly {
            get {
                return ResourceManager.GetString("PluginTypeNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is busy. Please wait!.
        /// </summary>
        internal static string ProgramIsBusyPleaseWait {
            get {
                return ResourceManager.GetString("ProgramIsBusyPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project can not go offline.
        /// </summary>
        internal static string ProjectCanNotGoOffline {
            get {
                return ResourceManager.GetString("ProjectCanNotGoOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project can not go online.
        /// </summary>
        internal static string ProjectCanNotGoOnline {
            get {
                return ResourceManager.GetString("ProjectCanNotGoOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is online!.
        /// </summary>
        internal static string ProjectIsOnline {
            get {
                return ResourceManager.GetString("ProjectIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current project?.
        /// </summary>
        internal static string SaveProjectBeforeClosing {
            get {
                return ResourceManager.GetString("SaveProjectBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating views....
        /// </summary>
        internal static string UpdatingViews {
            get {
                return ResourceManager.GetString("UpdatingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View with Name &apos;{0}&apos; and Ident &apos;{1}&apos; already exists.
        /// </summary>
        internal static string ViewAlreadyExists {
            get {
                return ResourceManager.GetString("ViewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
